title: My personal blog - Yanan Zhou
email: zhouyanan@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wanyaner.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Yanan Zhou # add your name
author-pic: yanan-face.png
about-author: My name is Ya-Nan Zhou. I'm an advertising strategist but now turn to learn programming.

# Contact links
email: zhouyanan@yahoo.com # Add your Email address
phone: # Add your Phone number
website: wanyaner.github.io # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: wanyaner # Add your Github handle
twitter: '@zyn9181' # Add your Twitter handle
facebook: yananchow # Add your Facebook handle
instagram: oooooyanan # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: yanan # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
